FROM python:3.9-slim

COPY ./skuskaSpojenia.py .

RUN ["pip","install","langchain"]

RUN ["pip","install","langchain-openai"]

RUN ["pip","install","openai"]

CMD ["python3","skuskaSpojenia.py"]





